#! /usr/bin/env ruby

arg_path = ARGV[0]
abort 'require file path' unless arg_path

require 'vips'
require 'pathname'

class OutputPath
  def initialize(path)
    pn = Pathname.new(path)

    @parent = pn.parent
    @extname = pn.extname
    @basename = pn.basename(@extname)
  end

  def filename
    "f.#{@basename}#{@extname}"
  end

  def to_s
    (@parent + filename).to_s
  end
end

def add_frame(image, frame_size, bg: [255, 255, 255])
  image.embed(frame_size, frame_size, image.width + (frame_size * 2), image.height + (frame_size * 2), background: bg)
end

in_path = File.expand_path(arg_path)
out_path = OutputPath.new(in_path)

Vips::Image.new_from_file(in_path)
  .then { _1.resize(0.5) }
  .then { add_frame(_1, [_1.width, _1.height].sort.last * 0.11) }
  .then { add_frame(_1, 1, bg: [220, 220, 220]) }
  .then { _1.write_to_file(out_path.to_s) }
